# Generated by Django 3.2.9 on 2021-12-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='created',
        ),
    ]
