# Generated by Django 3.2.9 on 2021-12-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(null='True', upload_to='uploads'),
            preserve_default='True',
        ),
    ]
